betty = Shareholder.create(name: "Betty", city: Faker::Address.city)
charles = Shareholder.create(name: "Charles", city: Faker::Address.city)
denise = Shareholder.create(name: "Denise", city: Faker::Address.city)
frank = Shareholder.create(name: "Frank", city: Faker::Address.city)
johnathan = Shareholder.create(name: "Johnathan", city: Faker::Address.city)

apple = Stock.create(company_name: "Apple", abbreviation: "AAPL", price: 286)
facebook = Stock.create(company_name: "Facebook", abbreviation: "FB", price: 177)
microsoft = Stock.create(company_name: "Microsoft", abbreviation: "MSFT", price: 173)
netflix = Stock.create(company_name: "Netflix", abbreviation: "NFLX", price: 412)
twitter = Stock.create(company_name: "Twitter", abbreviation: "TWTR", price: 27)

Purchase.create(shareholder_id: betty.id, stock_id: netflix.id, quantity: 4)
Purchase.create(shareholder_id: betty.id, stock_id: twitter.id, quantity: 2)
Purchase.create(shareholder_id: charles.id, stock_id: microsoft.id, quantity: 6)
Purchase.create(shareholder_id: charles.id, stock_id: twitter.id, quantity: 1)
Purchase.create(shareholder_id: charles.id, stock_id: apple.id, quantity: 4)
Purchase.create(shareholder_id: denise.id, stock_id: microsoft.id, quantity: 4)
Purchase.create(shareholder_id: frank.id, stock_id: netflix.id, quantity: 5)
Purchase.create(shareholder_id: johnathan.id, stock_id: apple.id, quantity: 8)
Purchase.create(shareholder_id: johnathan.id, stock_id: netflix.id, quantity: 2)
Purchase.create(shareholder_id: johnathan.id, stock_id: facebook.id, quantity: 1)
